=== KNIGHTTH0R/express-booking-selfconnect-api/schemas/booking-submit-response.json
{
  "title": "Booking Submit",
  "description": "Schema of an booking submit.",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "reference_id": {
      "type": "string"
    },
    "status": {
      "enum": [ "Success", "Failure", "PaymentPending" ]
    },
    "reservation": {
      "$ref": "reservation.json#"
    },
    "authorisation": {
      "$ref": "authorisation.json#"
    },
    "customer_support": {
      "$ref": "customer-support.json#"
    },
    "problems": {
      "type": "array",
      "items": {
        "$ref": "problem.json#"
      }
    }
  },
  "required": [ "reference_id", "status", "customer_support" ],
  "additionalProperties": true
}

=== KNIGHTTH0R/express-booking-selfconnect-api/examples/booking-submit/response-payment-pending.json
{
  "reference_id": "ae79eb46-0048-4c5b-98f4-9a1225589ff5",
  "status": "PaymentPending",
  "authorisation": {
    "reservation_id": "61382b72-546e-465d-82e3-61eb3829727e",
    "partner_data": {
      "transaction_id": "1234"
    },
    "target": {
      "url": "http://www.psp.test/auth",
      "method": "POST",
      "parameters": {
        "id1": "value1",
        "id2": "value2",
        "id3": "value3"
      }
    }
  },
  "customer_support": {
    "phone_numbers": [
      {
        "contact": "1-153-072-9237 x6907",
        "description": "Tempora iure sit accusamus et cupiditate autem reiciendis iusto."
      },
      {
        "contact": "015.409.9218",
        "description": "Commodi aut quia molestiae ut."
      }
    ],
    "emails": [
      {
        "contact": "Roxane.McKenzie@gmail.com",
        "description": "Aspernatur reiciendis quis at qui asperiores."
      }
    ],
    "urls": [
      {
        "contact": "http://kasey.info",
        "description": "Maiores enim cupiditate deserunt ut."
      },
      {
        "contact": "http://johann.biz",
        "description": "Rerum quae earum."
      }
    ]
  }
}

=== KNIGHTTH0R/express-booking-selfconnect-api/examples/booking-verify/response.json
{
  "reference_id": "692e8acc-d1d9-45dc-b50f-e7b824f3306f",
  "status": "Success",
  "reservation": {
    "reservation_id": "XXX123",
    "partner_reference": "abc123",
    "status": "Booked",
    "confirmation_url": "https://www.partner-hotel.com/confirm/XXX123",
    "checkin_date": "2016-01-25",
    "checkout_date": "2016-01-26",
    "hotel": {
      "name": "Some Awesome Hotel",
      "address1": "52977 Ismael Bridge",
      "city": "South Maurice",
      "state": "NY",
      "postal_code": "01234",
      "country": "USA",
      "latitude": -61.7414,
      "longitude": -174.122,
      "phone": "(509) 711-6896",
      "url": "http://www.hotel-site.com/welcome",
      "amenities": [
        "RESTAURANT",
        "NON_SMOKING",
        "FREE_PARKING"
      ],
      "checkinout_policy": "check-in from 3pm and check-out till 12am"
    },
    "customer": {
      "first_name": "Christopher",
      "last_name": "Palmer",
      "phone_number": "9-(590)311-9256",
      "email": "john@doe.com",
      "country": "US"
    },
    "rooms": [
      {
        "party": {
          "adults": 2,
          "children": [
            1
          ]
        },
        "traveler_first_name": "Christopher",
        "traveler_last_name": "Palmer"
      }
    ],
    "legal_text": "some legal stuff for confirmation",
    "comments": "special comment for confirmation",
    "receipt": {
      "line_items": [
        {
          "price": {
            "amount": 100,
            "currency": "USD"
          },
          "type": "rate",
          "paid_at_checkout": false,
          "description": "base price"
        },
        {
          "price": {
            "amount": 5,
            "currency": "USD"
          },
          "type": "tax",
          "paid_at_checkout": true,
          "description": "city tax"
        }
      ],
      "final_price_at_booking": {
        "amount": 100,
        "currency": "USD"
      },
      "final_price_at_checkout": {
        "amount": 5,
        "currency": "USD"
      }
    }
  },
  "customer_support": {
    "phone_numbers": [
      {
        "contact": "1-153-072-9237 x6907",
        "description": "Tempora iure sit accusamus et cupiditate autem reiciendis iusto."
      }
    ],
    "emails": [
      {
        "contact": "Roxane.McKenzie@gmail.com",
        "description": "Aspernatur reiciendis quis at qui asperiores."
      }
    ],
    "urls": [
      {
        "contact": "http://kasey.info",
        "description": "Maiores enim cupiditate deserunt ut."
      }
    ]
  }
}
