=== KNIGHTTH0R/express-booking-selfconnect-api/schemas/booking-prepare-request.json
{
    "title": "Booking Prepare",
    "description": "Schema of a booking preparation request.",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "api_version": {
            "type": "integer"
        },
        "checkin_date": {
            "type": "string"
        },
        "checkout_date": {
            "type": "string"
        },
        "partner_reference": {
            "type": "string"
        },
        "partner_data": {
            "$ref": "partner-data.json#"
        },
        "reference_id": {
            "type": "string"
        },
        "party": {
            "type": "array",
            "items": {
                "$ref": "party.json#"
            }
        }
    },
    "required": [
        "checkin_date",
        "checkout_date",
        "partner_reference",
        "partner_data",
        "party",
        "reference_id"
    ],
    "additionalProperties": true
}

=== KNIGHTTH0R/express-booking-selfconnect-api/examples/booking-prepare/request.json
{
  "checkin_date": "2018-01-25",
  "checkout_date": "2018-01-26",
  "partner_reference": "abc123",
  "reference_id": "692e8acc-d1d9-45dc-b50f-e7b824f3306f",
  "partner_data": {
    "identifier_for_something": "9614b191-9e1b-4b7d-9cbc-5b9204ac2a2a"
  },
  "party": [
    {
      "adults": 2,
      "children": [
        1
      ]
    }
  ]
}
